#!/bin/sh
#
# broadcast
# =========
# This is script which broadcast with ffmpeg.
# Sorry, this is for Linix only.
# # Required extra tools:
#  - ffmpeg ver.N-37669 or later (compiling with librtmp, libx264 and libfaac)
# 

RTMP_URI="$1"
STREAM="$2"
SCRIPTDIR=$(cd -P $(dirname "$0") && pwd -P)

# --- Load config files
if [ -e ${SCRIPTDIR}/config/global ]; then  
  . ${SCRIPTDIR}/config/global || exit 1
else
  echo "Can't open config/global file." >2
  exit 1
fi

BC_CONFFILE="${SCRIPTDIR}/config/broadcast.d/${BROADCASTER}"
if [ -e "${BC_CONFFILE}" ]; then
  . ${BC_CONFFILE}
else
  echo "Can't open ${BC_CONFFILE}" >2
  exit 2
fi

# --- Adjust parameter
if [ "${RTMP_URI}" = "test" ]; then
  FULL_OUTPUT_URI="${SCRIPTDIR}/test.flv"
else
  if [ -z "${STREAM}" ]; then 
    echo "Please specified RTMP_URI and STREAM."
    exit 3
  fi
  OUTPUT_URI="${RTMP_URI}/${STREAM}"
  RTMPPARAMS=$(echo "$RTMPPARAMS" | sed -e "s#@@RTMPURI@@#${OUTPUT_URI}#g")
  FULL_OUTPUT_URI="${OUTPUT_URI} ${RTMPPARAMS}"
fi

# --- Muxing video/audio and streaming to server.
FFMPEGFULLCOMMAND="${FFMPEG}
       ${FFMPEGDEBUG} -threads ${FFMPEGTHREADS}
       -f ${VIDEO_SRC_FMT} -i ${VIDEO_SRC_DEV}
       -f ${AUDIO_SRC_FMT} -i ${AUDIO_SRC_DEV}
       ${VCODEC_OPTS} ${ACODEC_OPTS} \
       ${OUTPUT_OPTS} ${FULL_OUTPUT_URI}"
/bin/echo -e "FFMPEG Command:\n" $FFMPEGFULLCOMMAND
exec $FFMPEGFULLCOMMAND


#        ${OUTPUT_OPTS} pipe: \
#   | ${FFMPEG} -y -re -i - -codec copy -f flv "${FULL_OUTPUT_URI}" \
#        -codec copy output.flv 

