#!/bin/sh
#
# broadcast
# =========
# This is script which broadcast with ffmpeg.
# Sorry, this is for Linix only.
# 
# Required extra tools:
#  - ffmpeg ver.N-37669 or later (compiling with librtmp, libx264 and libfaac)
# 

SOURCEDIR=$(dirname "$0")
RTMP_URI="$1"
STREAM="$2"

# --- Load config files
if [ -e ${SOURCEDIR}/config/global ]; then  
  . ${SOURCEDIR}/config/global || exit 1
else
  echo "Can't open config/global file." >2
  exit 1
fi
if [ -e ${SOURCEDIR}/config/broadcast.d/${BROADCASTER} ]; then
  . ${SOURCEDIR}/config/broadcast.d/${BROADCASTER}
else
  echo "Can't open config/broadcast.d/${BeOADCASTER}" >2
  exit 2
fi

# --- Adjust parameter
if [ "${RTMP_URI}" = "test" ]; then
  FULL_OUTPUT_URI="${SOURCEDIR}/test.flv"
else
  if [ -z "${STREAM}" ]; then 
    echo "Please specified RTMP_URI and STREAM."
    exit 3
  fi
  OUTPUT_URI="${RTMP_URI}/${STREAM}"
  RTMPPARAMS=$(echo "$RTMPPARAMS" | sed -e "s#@@RTMPURI@@#${OUTPUT_URI}#g")
  FULL_OUTPUT_URI="${OUTPUT_URI} ${RTMPPARAMS}"
fi

# --- Muxing video/audio and streaming to server.
exec \
${FFMPEG} ${FFMPEGDEBUG} -threads ${FFMPEGTHREADS} \
       -f ${VIDEO_SRC_FMT} -i ${VIDEO_SRC_DEV} \
       -f ${AUDIO_SRC_FMT} -i ${AUDIO_SRC_DEV} \
       ${VCODEC_OPTS} ${ACODEC_OPTS} \
       ${OUTPUT_OPTS} "${FULL_OUTPUT_URI}"
#        ${OUTPUT_OPTS} pipe: \
#   | ${FFMPEG} -y -re -i - -codec copy -f flv "${FULL_OUTPUT_URI}" \
#        -codec copy output.flv 

