#!/bin/sh

STARTX="${1:-0}"
STARTY="${2:-0}"
WIDTH="${3:-1024}"
HEIGHT="${4:-768}"
FRAMERATE="${5:-30/1}"
SINKDEV="${6:-/dev/video1}"

ENDX=$((${STARTX} + ${WIDTH} - 1))
ENDY=$((${STARTY} + ${HEIGHT} - 1))

exec \
gst-launch-1.0 \
    ximagesrc startx=${STARTX} starty=${STARTY} endx=${ENDX} endy=${ENDY} \
    ! "video/x-raw,width=${WIDTH},height=${HEIGHT},framerate=${FRAMERATE}" \
    ! videoconvert ! "video/x-raw,format=YUY2" \
    ! v4l2sink device=${SINKDEV} sync=0
