#!/bin/sh
BASEDIR=$(cd -P $(dirname "$0"); pwd -P)

. $BASEDIR/shlib/functions.sh

include ${BASEDIR}/config/global.conf

load_kmod_if_not v4l2loopback ${V4L2LOOPBACK_OPTIONS}

exec_if_exist guvcview -d "${CAMERADEVICE}" -z >/dev/null 2>&1 &
exec_if_exist pavucontrol &
exec_if_exist ${BASEDIR}/v4l2mixer &
