#!/bin/sh
SOURCEDIR=$(dirname "$0")

if [ ${SOURCEDIR}/config/global ]; then
  . ${SOURCEDIR}/config/global
else
  echo "Can't open config file." >2
  exit 1
fi

# --- Install v4l2loopback module
grep -q v4l2loopback /proc/modules >/dev/null 2>&1
if [ "$?" != "0" ]; then
   sudo modprobe v4l2loopback
fi

guvcview -d "${CAMERADEVICE}" -o >/dev/null 2>&1 &
pavucontrol &
python ${SOURCEDIR}/tool/webcamcomposer.py &


