#!/bin/sh
BASEDIR=$(dirname "$0")

if [ -e ${BASEDIR}/config/global ]; then
  . ${BASEDIR}/config/global
else
  echo "Can't open config file." >2
  exit 1
fi

check_loaded_kernelmodule() {
    grep -q v4l2loopback "$1" /proc/modules >/dev/null 2>&1
}

if ! check_loaded_kernelmodule v4l2loopback; then
   sudo modprobe v4l2loopback ${V4L2LOOPBACK_OPTIONS}
fi

guvcview -d "${CAMERADEVICE}" -o >/dev/null 2>&1 &
pavucontrol &
${BASEDIR}/v4l2mixer &


