#!/bin/sh
#
# Record.sh 
# =========
# this is script which recording with a webcam.
# 

SOURCEDIR=$(dirname "$0")
OUTPUT_FILE="${1:-record.dat}"

if [ -e ${SOURCEDIR}/config/global ]; then
  . ${SOURCEDIR}/config/global
else
  echo "Can't open config/global file." >2
  exit 1
fi

${FFMPEG} -y -threads 0 \
       -f ${VIDEO_SRC_FMT} -i ${VIDEO_SRC_DEV} \
       -f ${AUDIO_SRC_FMT} -i ${AUDIO_SRC_DEV} \
       -vcodec utvideo -q 20 \
       -acodec flac -aq 6 \
       -f matroska \
       "${OUTPUT_FILE}" &
wait

