#!/bin/sh

# Record.sh
# =========
# this is script which recording from a v4l2 device.

SCRIPTDIR=$(cd -P $(dirname "$0") && pwd -P)

NOWTIME=$(date +'%Y%m%d%H%M%S')
GLOBALCONF="${SCRIPTDIR}/config/global.conf"
OUTPUTDIR="${HOME}/Videos/Source"
OUTPUTFILE="${OUTPUTDIR}/record-${NOWTIME}.mkv"

FFMPEG_VCODECOPTS='-vcodec libx264 -q 20 -preset fast -tune zerolatency'
FFMPEG_ACODECOPTS='-acodec flac'
OUTPUT_OPTS='-f matroska'

log() {
    echo "$1" >2 
}

if [ ! -e "${GLOBALCONF}" ]; then
  log "Can't open ${GLOBALCONF}."
  exit 1
fi

. "${GLOBALCONF}"

[ -d "${OUTPUTDIR}" ] || mkdir "${OUTPUTDIR}"

exec ${FFMPEG} -y -threads 0 \
     -f ${VIDEO_SRC_FMT} -i ${VIDEO_SRC_DEV} \
     -f ${AUDIO_SRC_FMT} -i ${AUDIO_SRC_DEV} \
     ${FFMPEG_VCODECOPTS} \
     ${FFMPEG_ACODECOPTS} \
     ${OUTPUT_OPTS} \
     "${OUTPUTFILE}"

