#!/usr/bin/env python
# coding: utf-8
# vim: expandtab ts=2 sts=2 sw=2

# Copyright (c) 2011-2013, Yusuke Ohshima <createtool@yukke.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#   - Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#
#   - Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import print_function

import os
import sys
import codecs
import shlex
import subprocess
import signal
import tempfile
try:
  import ujson as json
except ImportError:
  try:
    import simplejson as json
  except ImportError:
    import json
try:
  import cPickle as pickle
except ImportError:
  import pickle
try:
  import cStringIO as StringIO
except:
  import StringIO

import pygtk
pygtk.require('2.0')
import gtk
import glib

import pygst
pygst.require('0.10')
import gst


SETTING_FILENAME = os.path.expanduser('~/.cameracapturerc')
N_TELOPS = 12


_CCS_FORMAT = {
  'MJPEG'  : 0,
  'RAW/YUV': 1,
}

_CCS_HALIGN = {
  'left'   : 0,
  'center' : 1,
  'right'  : 2,
}

_CCS_VALIGN = {
  'top'    : 0,
  'center' : 1,
  'bottom' : 2,
}

def debugmsg(msg):
 sys.stderr.write(msg+"\n")


class TelopSetting(object):
  def __init__(self,
               valignment=None, halignment=None, linealignment=None,
               xpad=None, ypad=None, fontdesc=None, text=None,
               is_cmd=False, silent=False, *args, **kw):
      self.valignment = valignment
      self.halignment = halignment
      self.linealignment = linealignment
      self.xpad = xpad
      self.ypad = ypad
      self.fontdesc = fontdesc
      self.text = text
      self.is_cmd = is_cmd
      self.silent = silent

def CreateDefaultTelopSetting():
  return TelopSetting(
      valignment = 'top',
      halignment = 'left',
      linealignment = 'left',
      xpad = '0',
      ypad = '0',
      fontdesc = 'Sans 10',
      text = '')


class V4l2ComposerSetting(object):
  SETTING_LATEST_VERSION = '1.1'

  def __init__(self):
    self._version = self.SETTING_LATEST_VERSION
    self.source_device = '/dev/video0'
    self.source_format = 'MJPEG'
    self.source_width = '640'
    self.source_height = '480'
    self.source_framerate = '30/1'
    self.sink_device = '/dev/video1'
    self.telops = [ CreateDefaultTelopSetting() 
                      for i in xrange(N_TELOPS) ]
    self.frame_svgfile = ''

  def Save(self, filename):
    with open(filename, "wb") as f:
      pickle.dump(self, f, -1)
    debugmsg("Settings saved to {0}.".format(SETTING_FILENAME))

  @staticmethod
  def Load(filename):
    try:
      with open(filename, "rb") as f:
        o = pickle.load(f)
      if isinstance(o, V4l2ComposerSetting):
        if len(o.telops) < N_TELOPS:
          o.telops = o.telops + [ CreateDefaultTelopSetting()
                      for i in xrange(N_TELOPS - len(o.telops)) ]
        elif len(o.telops) > N_TELOPS:
          o.telops = o.telops[:N_TELOPS]
        return o
      else:
        print("Read the data is not V4l2ComposerSetting type.")
        return V4l2ComposerSetting()
    except:
      return V4l2ComposerSetting()


class V4l2Composer(object):
  def __init__(self, setting, prev_panel=None, on_err_callback=None):
    self.setting = setting
    self.prev_panel = prev_panel
    self.on_err_callback = on_err_callback
    self.build_composer()

  def build_composer(self):
    #################
    # Make Elements #
    #################
    self.player = gst.Pipeline('V4l2Composer')
    #--
    self.camerasource = gst.element_factory_make('v4l2src')
    self.framesvg = gst.element_factory_make('rsvgoverlay')
    self.textoverlays = [ gst.element_factory_make('textoverlay') for i in xrange(N_TELOPS) ]
    self.v4l2sink = gst.element_factory_make('v4l2sink')
    self.monitorsink= gst.element_factory_make('xvimagesink')
    #--
    if self.setting.source_format == "MJPEG":
      sourcedecoder = gst.element_factory_make('jpegdec')
    else:
      sourcedecoder = None
    #--
    capsfilter = gst.element_factory_make('capsfilter')
    capsfilter2 = gst.element_factory_make('capsfilter')
    videorate = gst.element_factory_make('videorate')
    videorate2 = gst.element_factory_make('videorate')
    tee = gst.element_factory_make('tee')
    queue = gst.element_factory_make('queue')
    queue2 = gst.element_factory_make('queue')
    queue3 = gst.element_factory_make('queue')
    colorspace1 = gst.element_factory_make('ffmpegcolorspace')
    colorspace2 = gst.element_factory_make('ffmpegcolorspace')
    colorspace3 = gst.element_factory_make('ffmpegcolorspace')

    ########################
    # Configuring Elements #
    ########################
    # v4l2src property
    self.camerasource.set_property('device', self.setting.source_device)
    #self.camerasource.set_property('always-copy', False)
    #self.camerasource.set_property('queue-size', 4)
    self.camerasource.set_property('blocksize', 65536)

    # caps property
    if self.setting.source_format == "MJPEG":
      fmt = "image/jpeg"
    else:
      fmt = "video/x-raw-yuv"
    srccaps = '{0},width={1},height={2},framerate={3}' \
               .format(fmt,
                       self.setting.source_width,
                       self.setting.source_height,
                       self.setting.source_framerate)
    capsfilter.set_property('caps', gst.caps_from_string(srccaps))
    capsfilter2.set_property('caps', 
                             gst.caps_from_string('video/x-raw-yuv,format=(fourcc)YUY2'))

    # queue
    #queue.set_property('leaky', 2)

    # v4l2sink
    self.v4l2sink.set_property('device', self.setting.sink_device)
    self.v4l2sink.set_property('norm', 0)
    self.v4l2sink.set_property('sync', False)

    # textoverlay
    for i in xrange(N_TELOPS):
      telop_prop = self.setting.telops[i]
      self.SetTelopAtrribute(i, telop_prop)
      if telop_prop.is_cmd:
        self.SetTelopText(i, "")
      else:
        self.SetTelopText(i, telop_prop.text)

    # rsvgoverlay
    self.framesvg.set_property("location", self.setting.frame_svgfile)

    # sink
    self.monitorsink.set_property("sync", False)

    ####################
    # Linking Elements #
    ####################
    source_elements = [
      e for e in [
        self.camerasource,
        capsfilter,
        queue,
        sourcedecoder,
        colorspace1,
        self.framesvg, ]
      + self.textoverlays
      + [ tee ]
      if e is not None 
    ]

    v4l2output_elements = [
      queue2,
      colorspace2,
      capsfilter2,
      self.v4l2sink
    ]

    monitor_elements = [
      queue3,
      colorspace3,
      self.monitorsink
    ]

    self.player.add(
      *(source_elements
        + v4l2output_elements
        + monitor_elements)
    )
    gst.element_link_many(*source_elements)
    gst.element_link_many(tee, *v4l2output_elements)
    gst.element_link_many(tee, *monitor_elements)

    ########################
    # Connecting Callbacks #
    ########################
    bus = self.player.get_bus()
    bus.add_signal_watch()
    bus.enable_sync_message_emission()
    bus.connect("message", self.on_message)
    bus.connect("sync-message::element", self.on_sync_message)

  # Controller for Pipeline
  def Play(self):
    self.player.set_state(gst.STATE_PLAYING)

  def Pause(self):
    self.player.set_state(gst.STATE_PAUSED)

  def Stop(self):
    self.player.set_state(gst.STATE_NULL)

  # TextOverlay
  def SetTelopText(self, no, text):
    try:
      textoverlay = self.textoverlays[no]
    except IndexError:
      return
    else:
      textoverlay.set_property("text", text)

  def SetTelopAtrribute(self, no, telop_prop):
    try:
      textoverlay = self.textoverlays[no]
    except IndexError:
      return
    else:
      if telop_prop.halignment is not None:
        textoverlay.set_property("halignment", telop_prop.halignment)
      if telop_prop.valignment is not None:
        textoverlay.set_property("valignment", telop_prop.valignment)
      if telop_prop.linealignment is not None:
        textoverlay.set_property("line-alignment", telop_prop.linealignment)
      if telop_prop.fontdesc is not None:
        textoverlay.set_property("font-desc", telop_prop.fontdesc)
      if telop_prop.xpad is not None:
        textoverlay.set_property("xpad", int(telop_prop.xpad))
      if telop_prop.ypad is not None:
        textoverlay.set_property("ypad", int(telop_prop.ypad))
      if telop_prop.silent is not None:
        textoverlay.set_property("silent", telop_prop.silent)
      if telop_prop.fontdesc is not None:
        textoverlay.set_property("font-desc", telop_prop.fontdesc)
      if telop_prop.text is not None:
        textoverlay.set_property("text", telop_prop.text)

      textoverlay.set_property("shadow",False)

  # RSvgOverlay
  def SetFrameSvgFile(self, filepath):
    self.framesvg.set_property("location", filepath)

  #############
  # Callbacks #
  #############
  def on_message(self, bus, message):
    type = message.type
    if type == gst.MESSAGE_EOS:
      self.Stop()
    elif type == gst.MESSAGE_ERROR:
      self.Stop()
      msg = message.parse_error()
      if self.on_err_callback and callable(self.on_err_callback):
        self.on_err_callback(msg)

  def on_sync_message(self, bus, message):
    if message.structure is None:
      return
    message_name = message.structure.get_name()
    if message_name == "prepare-xwindow-id":
      imagesink = message.src
      imagesink.set_property("force-aspect-ratio", True)
      if self.prev_panel:
        gtk.gdk.threads_enter()
        imagesink.set_xwindow_id(self.prev_panel.window.xid) 
        gtk.gdk.threads_leave()


class SpawnStdoutReader(object):
  def __init__(self, commandline,
               init_callback=None, read_callback=None, term_callback=None,
               callback_args=None):
    self.commandline = commandline
    self.init_callback = init_callback
    self.read_callback = read_callback
    self.term_callback = term_callback
    self.callback_args = callback_args
    self.child = None

  def run(self):
    try:
      self.child = subprocess.Popen(self.commandline,
                                    stdout=subprocess.PIPE,
                                    close_fds=True)
    except OSError as e:
      print(e.message)
      return
    try:
      glib.io_add_watch(self.child.stdout,
                        glib.IO_IN | glib.IO_HUP,
                        self._eventHandler)
    except glib.GError as e:
      self.terminate()
    if self.init_callback:
      self.init_callback(self.callback_args)

  def _eventHandler(self, fd, condition):
    if condition & glib.IO_IN:
      buf = StringIO.StringIO()
      while True:
        data = fd.read(1)
        buf.write(data)
        if data == "\0" or len(data) == 0:
          break
      if self.read_callback:
        self.read_callback(buf.getvalue(), self.callback_args)
      buf.close()

    if condition & glib.IO_HUP:
      if self.child:
        self.child.poll()
        if self.term_callback:
          self.term_callback(self.callback_args)
        return False
    return True

  def getpid(self):
    pid = -1
    if self.child:
      pid = self.child.pid
    return pid

  def terminate(self):
    if self.child:
      self.child.terminate()

  def is_running(self):
    if self.child:
      return bool(self.child.returncode is None)
    return False


class V4l2ComposerWindow(gtk.Window):
  def __init__(self, setting):
    gtk.Window.__init__(self, gtk.WINDOW_TOPLEVEL)

    self.setting = setting
    self.player = None
    self.spawnlist = [None] * N_TELOPS

    self.build_window()
    self.set_values()

  def build_window(self):
    self.set_title("V4l2 Comporser")
    self.set_default_size(800, 600)
    self.connect("delete-event", self.on_delete)
    self.connect("destroy", self.on_destroy)

    vbox_root = gtk.VBox()
    self.add(vbox_root)

    vbox_main = gtk.VBox()
    vbox_main.set_spacing(8)
    vbox_root.pack_start(vbox_main, True)

    vbox_main.pack_start(self.build_camera_box(), True)
    vbox_main.pack_start(self.build_frame_box(), False)
    vbox_main.pack_start(self.build_telop_box(), False)

    self.show_all()

  def build_camera_box(self):
    vbox = gtk.VBox()

    hbox = gtk.HBox()
    hbox.set_spacing(8)
    vbox.pack_start(hbox, False)

    hbox.pack_start(gtk.Label("Src:"), False)
    self.ent_camera_src = gtk.Entry()
    self.ent_camera_src.set_size_request(100, -1)
    hbox.pack_start(self.ent_camera_src, False)

    hbox.pack_start(gtk.Label("Fmt:"), False)
    self.cmb_camera_fmt= gtk.combo_box_new_text()
    self.cmb_camera_fmt.append_text("MJPEG")
    self.cmb_camera_fmt.append_text("RAW/YUV")
    hbox.pack_start(self.cmb_camera_fmt, False)

    hbox.pack_start(gtk.Label("Width:"), False)
    self.ent_camera_width = gtk.Entry()
    self.ent_camera_width.set_size_request(50, -1)
    hbox.pack_start(self.ent_camera_width, False)

    hbox.pack_start(gtk.Label("Height:"), False)
    self.ent_camera_height = gtk.Entry()
    self.ent_camera_height.set_size_request(50, -1)
    hbox.pack_start(self.ent_camera_height, False)

    hbox.pack_start(gtk.Label("FPS:"), False)
    self.ent_camera_fps = gtk.Entry()
    self.ent_camera_fps.set_size_request(50, -1)
    hbox.pack_start(self.ent_camera_fps, False)

    hbox.pack_start(gtk.Label("Sink:"), False)
    self.ent_sink = gtk.Entry()
    self.ent_sink.set_size_request(100, -1)
    hbox.pack_start(self.ent_sink, False)

    self.btn_camera_tgl = gtk.ToggleButton("Off")
    self.btn_camera_tgl.connect("toggled", self.on_camera_startstop)
    hbox.pack_start(self.btn_camera_tgl, True)

    self.movie_window = gtk.DrawingArea()
    vbox.pack_start(self.movie_window, True)

    return vbox

  def build_frame_box(self):
    vbox = gtk.VBox()

    hbox = gtk.HBox()
    hbox.set_spacing(8)
    vbox.pack_start(hbox, False)

    hbox.pack_start(gtk.Label("Frame SVG :"), False)
    self.setframe_btn = gtk.FileChooserButton("Set Frame from SVG")
    self.setframe_btn.connect("file-set", self.on_setframe_fileset)
    hbox.pack_start(self.setframe_btn, True)

    return vbox

  def build_telop_box(self):
    vbox = gtk.VBox()
    vbox.set_spacing(8)

    hbox = gtk.HBox()
    hbox.set_spacing(8)
    vbox.pack_start(hbox, True)

    hbox.pack_start(gtk.Label("TNO."), False)
    self.cmb_text_idx = gtk.combo_box_new_text()
    self.cmb_text_idx.connect('changed', self.on_cmb_text_idx_changed)
    hbox.pack_start(self.cmb_text_idx, True)
    for i in xrange(N_TELOPS):
      self.cmb_text_idx.append_text(str(i))

    hbox.pack_start(gtk.Label("V:"), False)
    self.cmb_text_valign = gtk.combo_box_new_text()
    hbox.pack_start(self.cmb_text_valign, True)
    self.cmb_text_valign.append_text("top")
    self.cmb_text_valign.append_text("center")
    self.cmb_text_valign.append_text("bottom")

    hbox.pack_start(gtk.Label("H:"), False)
    self.cmb_text_halign = gtk.combo_box_new_text()
    hbox.pack_start(self.cmb_text_halign, True)
    self.cmb_text_halign.append_text("left")
    self.cmb_text_halign.append_text("center")
    self.cmb_text_halign.append_text("right")

    hbox.pack_start(gtk.Label("Line:"), False)
    self.cmb_text_lalign = gtk.combo_box_new_text()
    hbox.pack_start(self.cmb_text_lalign, True)
    self.cmb_text_lalign.append_text("left")
    self.cmb_text_lalign.append_text("center")
    self.cmb_text_lalign.append_text("right")

    hbox.pack_start(gtk.Label("X-pad:"), False)
    self.ent_text_xpad = gtk.Entry()
    self.ent_text_xpad.set_size_request(50, -1)
    hbox.pack_start(self.ent_text_xpad, True)

    hbox.pack_start(gtk.Label("Y-pad:"), False)
    self.ent_text_ypad = gtk.Entry()
    self.ent_text_ypad.set_size_request(50, -1)
    hbox.pack_start(self.ent_text_ypad, True)

    hbox2 = gtk.HBox()
    vbox.pack_start(hbox2, True)
    vbox.set_spacing(8)

    self.chk_text_is_cmdline = gtk.CheckButton("Command")
    self.chk_text_is_cmdline.set_alignment(0, 0)
    hbox2.pack_start(self.chk_text_is_cmdline, False)

    self.btn_exec = gtk.Button("Exec")
    self.btn_exec.connect("clicked", self.on_exec_subprocess)
    self.btn_exec.set_sensitive(True)
    hbox2.pack_start(self.btn_exec, False)

    self.btn_kill = gtk.Button("Kill")
    self.btn_kill.connect("clicked", self.on_kill_subprocess)
    self.btn_kill.set_sensitive(False)
    hbox2.pack_start(self.btn_kill, False)

    hbox2.pack_start(gtk.Label("Display Font:"), False)
    self.fontselector = gtk.FontButton();
    self.fontselector.connect("font-set", self.on_font_set)
    hbox2.pack_start(self.fontselector, False)

    self.btn_update = gtk.Button("Update")
    self.btn_update.set_property("width-request", 200)
    self.btn_update.connect("clicked", self.on_update)
    hbox2.pack_end(self.btn_update, False)

    self.chk_silent = gtk.CheckButton("Silent")
    hbox2.pack_end(self.chk_silent, False)

    scroll_text_view = gtk.ScrolledWindow()
    scroll_text_view.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)
    self.ent_text = gtk.TextView()
    self.ent_text.set_size_request(-1, 64)
    scroll_text_view.add(self.ent_text)
    vbox.pack_start(scroll_text_view, True)

    return vbox

  def set_values(self):
    self.ent_camera_src.set_text(self.setting.source_device)
    self.cmb_camera_fmt.set_active(_CCS_FORMAT.get(self.setting.source_format, 0))
    self.ent_camera_width.set_text(self.setting.source_width)
    self.ent_camera_height.set_text(self.setting.source_height)
    self.ent_camera_fps.set_text(self.setting.source_framerate)
    self.ent_sink.set_text(self.setting.sink_device)
    self.setframe_btn.set_filename(self.setting.frame_svgfile)
    self.cmb_text_idx.set_active(0)

  ###############
  #  Callbacks  #
  ###############

  # -- Callback for events

  def on_cmb_text_idx_changed(self, widget):
    idx = widget.get_active()
    try:
      telop = self.setting.telops[idx]
    except IndexError:
      return

    self.cmb_text_halign.set_active(_CCS_HALIGN.get(telop.halignment, 0))
    self.cmb_text_valign.set_active(_CCS_VALIGN.get(telop.valignment, 0))
    self.cmb_text_lalign.set_active(_CCS_HALIGN.get(telop.linealignment, 0))
    self.ent_text_xpad.set_text(str(telop.xpad))
    self.ent_text_ypad.set_text(str(telop.ypad))
    self.chk_text_is_cmdline.set_active(telop.is_cmd)
    self.chk_silent.set_active(telop.silent)
    self.fontselector.set_font_name(telop.fontdesc)
    self.ent_text.get_buffer().set_text(telop.text)

    isrun = False
    if telop.is_cmd:
      spawn = self.spawnlist[idx]
      if spawn:
        isrun = spawn.is_running()
    self.btn_exec.set_sensitive(not isrun)
    self.btn_kill.set_sensitive(isrun)


  def on_update(self, widget, *args):
    idx = self.cmb_text_idx.get_active()
    if idx < 0:
      return
    telop = self.setting.telops[idx]
    telop.halignment = self.cmb_text_halign.get_active_text()
    telop.valignment = self.cmb_text_valign.get_active_text()
    telop.linealignment = self.cmb_text_lalign.get_active_text()
    telop.xpad = int(self.ent_text_xpad.get_text())
    telop.ypad = int(self.ent_text_ypad.get_text())
    telop.is_cmd = self.chk_text_is_cmdline.get_active()
    telop.silent = self.chk_silent.get_active()
    telop.fontdesc = self.fontselector.get_font_name()
    telop.text = self.GetTextViewValue(self.ent_text)
    if self.player:
      self.player.SetTelopAtrribute(idx, telop)

  def on_camera_startstop(self, widget):
    if widget.get_active():
      self.setting.source_device = self.ent_camera_src.get_text()
      self.setting.source_format = self.cmb_camera_fmt.get_active_text()
      self.setting.source_width = self.ent_camera_width.get_text()
      self.setting.source_height = self.ent_camera_height.get_text()
      self.setting.source_framerate = self.ent_camera_fps.get_text()
      self.setting.sink_device = self.ent_sink.get_text()

      self.player = V4l2Composer(self.setting,
                                 prev_panel=self.movie_window,
                                 on_err_callback=self.on_webcamcomposer_error)
      self.player.Play()
      self.btn_camera_tgl.set_label("On")
    else:
      self.player.Stop()
      self.player = None
      self.btn_camera_tgl.set_label("Off")

  def on_exec_subprocess(self, widget):
    idx = self.cmb_text_idx.get_active()
    if idx < 0:
      return
    telop = self.setting.telops[idx]
    if telop.is_cmd:
      if self.spawnlist[idx]:
        if self.spawnlist[idx].is_running():
          return
        else:
          self.spawnlist[idx] = None
      cmdline = shlex.split(telop.text)
      s = SpawnStdoutReader(cmdline,
                            init_callback=self.on_init_subprocess,
                            read_callback=self.on_read_pipe,
                            term_callback=self.on_term_subprocess,
                            callback_args=None)
      s.run()
      self.spawnlist[idx] = s

  def on_kill_subprocess(self, widget):
    no = self.cmb_text_idx.get_active()
    sl = self.spawnlist[no]
    if sl and sl.is_running():
      debugmsg("Terminated subprocess: {0}.".format(sl.getpid()))
      sl.terminate()

  def on_delete(self, widget, *args):
    debugmsg("OnDelete is called.")
    if self.player:
      self.player.Stop()
    for s in self.spawnlist:
      if s and s.is_running():
        s.terminate()
    return False

  def on_destroy(self, widget, *args):
    debugmsg("OnDestroy is called.")
    gtk.main_quit()

  def on_font_set(self, widget):
    font_name = widget.get_font_name()
    debugmsg("Set font is '{0}'.".format(font_name))

  def on_setframe_fileset(self, widget, *args):
    filepath = widget.get_filename()
    if self.player:
      self.player.SetFrameSvgFile(filepath)
    self.setting.frame_svgfile = filepath
    debugmsg("load frame svg file: {0}".format(filepath))


  # -- External
  def on_webcamcomposer_error(self, message):
    """ V4l2Composer Error Callback """
    debugmsg("{0}:{1}".format(*message))
    self.btn_camera_tgl.set_active(False)
    self.btn_camera_tgl.set_label("Off")

  # -- SpawnStdoutReader callbacks
  def on_init_subprocess(self, args):
    self.btn_exec.set_sensitive(False)
    self.btn_kill.set_sensitive(True)

  def on_term_subprocess(self, args):
    self.btn_exec.set_sensitive(True)
    self.btn_kill.set_sensitive(False)

  def on_read_pipe(self, texts, args):
    if not self.player:
      return
    results = jsonProcessor(texts)
    for idx, ts in results:
      self.player.SetTelopAtrribute(idx, ts)


  ##########
  #  Misc  #
  ##########
  def GetTextViewValue(self, textview):
    buf = textview.get_buffer()
    start, end = buf.get_bounds()
    text = buf.get_text(start, end)
    return text


def jsonProcessor(texts):
  result = []
  def switchGroup(_v, _a):
    if isinstance(v, list):
      for _i in _v:
        try:
          _i = int(_i)
        except ValueError:
          continue
        else:
          _ts = TelopSetting(silent=_a)
          result.append((_i, _ts))

  for text in texts.split("\0"):
    try:
      parsedata = json.loads(text)
    except ValueError:
      continue
    else:
      if isinstance(parsedata, dict):
        for k, v in parsedata.iteritems():
          if k == 'framesvg':
            if os.path.exists(v):
              result.appenda(('framesvg', v))
          elif k == 'hides':
            switchGroup(v, True)
          elif k == 'shows':
            switchGroup(v, False)
          else:
            ts = TelopSetting()
            if isinstance(d, dict):
              for k2, v2 in v.iteritems():
                if k == 'text':
                  ts.text = v2
                if k == 'silent':
                  ts.silent = v2
              result.append((k, ts))
            elif isinstance(v, (str, unicode)):
              ts.text = v
              result.append((k, ts))
  return result


def main():
  gtk.gdk.threads_init()
  setting = V4l2ComposerSetting.Load(SETTING_FILENAME)
  cm = V4l2ComposerWindow(setting)
  try:
    gtk.main()
  except:
    raise
  setting.Save(SETTING_FILENAME)


if __name__ == "__main__":
  main()

